version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    ports:
      - "4533:4533"
    environment:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_BASEURL=/
      - ND_UITHEME_FILE=/custom.css
    volumes:
      - "./data:/data"
      - "/home/admin/music:/music:ro"
      - "/home/admin/navidrome-custom/sonicwave-theme.css:/custom.css:ro"